Change workflow_builder function to compose_workflow which returns Wo…
FRINXio/frinx-python-sdk pull request #6
Opened 2023-05-19 12:23 UTC by daviddzxy

…rkflowTaskImpl list

2023-05-22 09:41 UTC, Jozefiel approved these changes

2023-05-22 12:31 UTC, marosmars approved these changes

2023-05-22 12:34 UTC, marosmars requested changes
Where would I set the output params now ?

```        
self.tasks.append(routes_lambda)

self.output_parameters[ROUTE_STATS] = routes_lambda.output_ref("result")
```

2023-05-22 12:47 UTC, dav1d-b commented
> Where would I set the output params now ? I mean, this is how I do it now: Maybe we should do something about the output params setup as well
> 
> ```
> self.tasks.append(routes_lambda)
> 
> self.output_parameters[ROUTE_STATS] = routes_lambda.output_ref("result")
> ```
Yep, we should also encapsulate output_parameters. I will think about this.

2023-05-23 09:53 UTC, Jozefiel commented
In my opinion, this change is a limiting.
In the original version, it is possible to dynamically change all workflow parameters and introduce higher logic. For example, it is possible to set default input parameters based on ENV variables or some request.
I would not limit it only to creating tasks.

2023-05-29 15:13 UTC, closed without merging